dataset:
  name: KITTILoader
  root_path: datasets/data_odometry_gray/dataset
  sequence: '00'
  start: 0
  max_frames: 1500

detector:
  name: SwiftFeatDetector
  top_k: 4096
  detection_threshold: 0.05
  weights: third_party/swiftfeat/weights/xfeat_default_169500_swiftfeatv5.pt
  cuda: 1

matcher:
  name: SwiftFeatLightGlueMatcher
  top_k: 4096
  min_conf: 0.1
  weights: third_party/swiftfeat/weights/xfeat_default_169500_swiftfeatv5.pt
  detection_threshold: 0.05
